name: eletro_store # Renomeado para "Eletro Store"
description: "A Flutter e-commerce app template."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/lo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/icon.jpg
    - assets/image/phone.jpeg
    - assets/image/fone.jpeg
    - assets/image/tv.jpeg
    - assets/image/liqui.jpeg
    - assets/image/Map.jpg  # Note a capitalização correta
    - assets/image/  # Inclui todos os arquivos da pasta